# Generated by Django 3.2.6 on 2021-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_my_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_type',
            field=models.JSONField(default={}),
        ),
    ]
